//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MauiAuthPageTemplate.Resources.Strings.AuthPageViewModelResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourcesAuthPageViewModel {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcesAuthPageViewModel() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MauiAuthPageTemplate.Resources.Strings.AuthPageViewModelResources.ResourcesAuthPa" +
                            "geViewModel", typeof(ResourcesAuthPageViewModel).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your login and password.
        /// </summary>
        public static string enter_login_and_password {
            get {
                return ResourceManager.GetString("enter_login_and_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error logging in via Facebook.
        /// </summary>
        public static string facebook_login_error {
            get {
                return ResourceManager.GetString("facebook_login_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error logging in via Google.
        /// </summary>
        public static string google_login_error {
            get {
                return ResourceManager.GetString("google_login_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid login or password.
        /// </summary>
        public static string invalid_login_or_password {
            get {
                return ResourceManager.GetString("invalid_login_or_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No internet connection.
        /// </summary>
        public static string no_internet_connection {
            get {
                return ResourceManager.GetString("no_internet_connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password reset error.
        /// </summary>
        public static string password_reset_error {
            get {
                return ResourceManager.GetString("password_reset_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration cancelled.
        /// </summary>
        public static string registration_cancelled {
            get {
                return ResourceManager.GetString("registration_cancelled", resourceCulture);
            }
        }
    }
}
